# Generated by Django 5.2.4 on 2025-08-07 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fix_admin_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrolled_at']},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='examattempt',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='feetransaction',
            options={'ordering': ['-transaction_date']},
        ),
        migrations.AlterModelOptions(
            name='studymaterial',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='url',
        ),
        migrations.AddField(
            model_name='examattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklydetail',
            name='schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('essay', 'Essay'), ('true_false', 'True/False'), ('short_answer', 'Short Answer')], default='multiple_choice', max_length=20),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='material_type',
            field=models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('link', 'Link'), ('presentation', 'Presentation'), ('assignment', 'Assignment'), ('pdf', 'PDF'), ('image', 'Image'), ('audio', 'Audio')], default='document', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('exam_attempt', 'question')},
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('study_material', 'Study Material'), ('assignment', 'Assignment'), ('exam', 'Exam'), ('profile_picture', 'Profile Picture'), ('course_thumbnail', 'Course Thumbnail'), ('other', 'Other')], max_length=20)),
                ('file_size', models.PositiveIntegerField()),
                ('related_model', models.CharField(blank=True, max_length=50, null=True)),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_uploads',
                'ordering': ['-created_at'],
            },
        ),
    ]
